services:
  # CONTAINER 1: The Visual UI Web App
  ai-frontend:
    build: .
    container_name: grocery_ai_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://ai-backend:11434
      # We add database credentials as environment variables for runtime security
      - DB_HOST=ai-database
      - DB_NAME=inventory_db
      - DB_USER=postgres
      - DB_PASSWORD=local_secure_pass
    depends_on:
      - ai-database
      - ai-backend

  # CONTAINER 2: The Isolated Local AI Engine
  ai-backend:
    image: ollama/ollama:latest
    container_name: grocery_ai_backend
    ports:
      - "11434"
    volumes:
      - ~/.ollama:/root/.ollama

  # CONTAINER 3: The Enterprise Data Layer
  ai-database:
    image: postgres:17-alpine
    container_name: grocery_ai_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local_secure_pass
    volumes:
      # This saves the relational records inside a dedicated Docker volume
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
